name: More-Recipes
version: "1.5-alpha-1"
author: DanTheTechMan
main: dansplugins.recipesystem.MoreRecipes
api-version: "1.13"

commands:
  morerecipes:
  mr:

permissions:
  morerecipes.listitems:
    default: true
  morerecipes.get:
    default: op