name: More-Recipes
version: '${project.version}'
author: Daniel McCoy Stephenson, Rykurock
main: dansplugins.recipesystem.MoreRecipes
api-version: "1.13"

commands:
  morerecipes:
  mr:

permissions:
  morerecipes.help:
    default: true
  morerecipes.listitems:
    default: true
  morerecipes.get:
    default: op